# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - bash: sudo apt update
    - bash: sudo apt install maven
    - bash: java -version
    - bash: mvn -version
    - script: |
        cd ./app-1/
        ls -la
        mvn clean package
        ls
        cd ./target/
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/app-1/target/app-1-0.0.1-SNAPSHOT.jar'
        ArtifactName: 'drop'
        publishLocation: 'Container'